#!/usr/bin/env python
################################################################################
#
#       This file is part of Gato (Graph Animation Toolbox) 
#
#	    file:   gato-create-js-css-symlinks
#	    author: Alexander Schliep
#
#       Copyright (C) 2020 Alexander Schliep

#       Contact: alexander@schliep.org
#
#       Information: http://gato.sf.net
#
#       This library is free software; you can redistribute it and/or
#       modify it under the terms of the GNU Library General Public
#       License as published by the Free Software Foundation; either
#       version 2 of the License, or (at your option) any later version.
#
#       This library is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#       Library General Public License for more details.
#
#       You should have received a copy of the GNU Library General Public
#       License along with this library; if not, write to the Free
#       Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
#
#
#       This file is version $Revision: 291 $ 
#                       from $Date: 2006-10-18 16:04:35 +0200 (Wed, 18 Oct 2006) $
#             last change by $Author: schliep $.
#
################################################################################

import os
from pkg_resources import resource_filename


jspath = resource_filename('Gato', 'svgs/js')
csspath = resource_filename('Gato', 'svgs/css')

print "# adding symlinks to %s and %s in working directory" % (jspath, csspath)
os.symlink(jspath, "./js")
os.symlink(csspath, "./css")
