/*
	WISHLIST:
1) Back-step button

*/

var snap = Snap("svg");
var g = {}; // globals


function add_snap_vars() {
	g.graph_elem_types = ['vertices', 'edges', 'code_lines', 'edge_arrows', 'highlight_boxes'];
	g.graph_elem_ids = ['vertex', 'edge', 'code_line', 'arrowhead'];
	// TODO: update this code to be mroe generic
	extend(g, {
		vertices: [{}, {}],
		edges: [{}, {}],
		edge_arrows: [{}, {}],
		graphs: []
	});
    var vertices = {}, edges = {}, edge_arrows = {}, code_lines = {};
    for (var graph_num=0; graph_num<g.num_graphs; graph_num++) {
        
        var v = snap.selectAll('g#g' + (graph_num+1) + ' .vertex');
        for (var i=0; i<v.length; i++) {
            g.vertices[graph_num][v[i].attr('id')] = v[i];
        }
        var e = snap.selectAll('g#g' + (graph_num+1) + ' .edge');
        for (var i=0; i<e.length; i++) {
            g.edges[graph_num][e[i].attr('id')] = e[i];
        }
        var ea = snap.selectAll('g#g' + (graph_num+1) + ' .arrowhead');
        for (var i=0; i<ea.length; i++) {
            g.edge_arrows[graph_num][ea[i].attr('id')] = ea[i];
        }
    }
    var lines = snap.selectAll('.code_line');
    g.code_lines = {};
    for (var i=0; i<lines.length; i++) { 
        g.code_lines[lines[i].attr('id')] = lines[i];
        // Mark it if the codeline is just whitespace
        var text = lines[i].attr('text');
        lines[i]['whitespace'] = text.length === 0;
    }
    g['graphs'].push(snap.select('g#g1'));
    var g2 = snap.select('g#g2');
    if (g2 != null) {
    	g['graphs'].push(g2);
    }
}

function extend(a, b) {
	for (var key in b) {
		a[key] = b[key];
	}
}

function fill_global() {
	//$.extend(g, {
	var cont_width = window.innerWidth;
	var cont_height = window.innerHeight;
	extend(g, {
		// Global 
		cont_width: cont_width,
		cont_height: cont_height,
        padding: Math.min(Math.ceil(cont_width*.02), Math.ceil(cont_height)*.02),

		// Graph 
		vertex_r: parseInt(snap.select('g#g1 .vertex').attr('r')),
        frame_padding: 8,
        graph_containers: [snap.group().attr({'id': 'g1_container'}),
        	snap.group().attr({'id': 'g2_container'})],
        graph_frame_stroke_width: 1,

        // General
    	arrow_id_prefix: 'ea',
	});
	if (snap.select('g#g2') != null) {
		g.num_graphs = 2;
	} else {
		g.num_graphs = 1;
	}
    g.master_graph_container = snap.group();
    for (var i=0; i<g.graph_containers.length; i++) {
        g.master_graph_container.append(g.graph_containers[i]);
    }

    add_snap_vars();
}

function save_initial_graph_dimensions() {
    var bbox = g.master_graph_container.getBBox();
    g.initial_graph_width = bbox.width;
    g.initial_graph_height = bbox.height;
}

function global_mouseup(evt) {
    if (g.scaler.scaling === true) {
        g.scaler.mouseup(evt);
    }
    if (g.slider.sliding === true) {
        g.slider.cursor_mouseup(evt);
    }
}

function global_mousemove(evt) {
	if (g.scaler.scaling === true) {
		g.scaler.mousemove(evt);
	}
	if (g.slider.sliding === true) {
		g.slider.cursor_mousemove(evt);
	}
}

function global_drag(evt) {
	if (g.scaler.scaling === true) {
		g.scaler.drag(evt);
	}
	if (g.slider.sliding === true) {
		g.slider.cursor_drag(evt);
	}
}

function init() {
    // Add global event handlers
    snap.mouseup(global_mouseup);
    snap.mousemove(global_mousemove);
    snap.drag(function(){}, function(){}, global_drag)

    // Set globals and size of base_container
    fill_global();
    document.getElementById('base_container').setAttribute('style', 'width: ' + g.cont_width + '; height: ' + g.cont_height);
    document.getElementById('svg').setAttribute('style', 'width: ' + g.cont_width + 'px; height: ' + g.cont_height + 'px');
    console.log("setting container to height: " + g.cont_height);
    // Initialize graphical elements
    g.playback_bar = new PlaybackBar();
    g.code_box = new CodeBox();
    add_graph_frame();
    position_graph();
    add_scaler();
    save_initial_graph_dimensions();

    // Build the GraphState array
    g.animation = new Animation();
}


var anim_array = Array(Array(1, SetAllVerticesColor, "g1_grey"),
Array(2, SetAllVerticesColor, "g2_grey"),
Array(2, ShowActive, "l_1"),
Array(1, UpdateEdgeInfo, "g1_11-16", "Edge11-16-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_14-17", "Edge14-17-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_1-3", "Edge1-3-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_8-13", "Edge8-13-flow:0of50"),
Array(1, UpdateEdgeInfo, "g1_4-8", "Edge4-8-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_7-12", "Edge7-12-flow:0of50"),
Array(1, UpdateEdgeInfo, "g1_10-15", "Edge10-15-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_13-17", "Edge13-17-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_12-16", "Edge12-16-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_3-7", "Edge3-7-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_2-5", "Edge2-5-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_1-2", "Edge1-2-flow:0of141"),
Array(1, UpdateEdgeInfo, "g1_4-9", "Edge4-9-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_13-16", "Edge13-16-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_15-18", "Edge15-18-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_16-18", "Edge16-18-flow:0of100"),
Array(1, UpdateEdgeInfo, "g1_2-6", "Edge2-6-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_9-14", "Edge9-14-flow:0of50"),
Array(1, UpdateEdgeInfo, "g1_3-6", "Edge3-6-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_6-11", "Edge6-11-flow:0of50"),
Array(1, UpdateEdgeInfo, "g1_1-4", "Edge1-4-flow:0of141"),
Array(1, UpdateEdgeInfo, "g1_17-18", "Edge17-18-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_5-10", "Edge5-10-flow:0of50"),
Array(1, UpdateEdgeInfo, "g1_3-8", "Edge3-8-flow:0of112"),
Array(1, UpdateEdgeInfo, "g1_11-15", "Edge11-15-flow:0of100"),
Array(1, UpdateGraphInfo, "g2_", ""),
Array(9, ShowActive, "l_9"),
Array(8, SetVertexAnnotation, "g1_1", "s"),
Array(3, SetVertexColor, "g2_1", "green"),
Array(2, ShowActive, "l_10"),
Array(8, SetVertexAnnotation, "g1_18", "t"),
Array(2, SetVertexColor, "g2_18", "red"),
Array(1, ShowActive, "l_12"),
Array(9, ShowActive, "l_13"),
Array(8, SetAllEdgesColor, "g2_#DDDDDD"),
Array(2, SetAllVerticesColor, "g2_#000099"),
Array(2, SetVertexColor, "g2_1", "#CFCFCF"),
Array(1, SetVertexColor, "g2_2", "#CFCFCF"),
Array(1, SetVertexColor, "g2_3", "#CFCFCF"),
Array(1, SetVertexColor, "g2_4", "#CFCFCF"),
Array(1, SetVertexColor, "g2_5", "#CFCFCF"),
Array(1, SetVertexColor, "g2_6", "#CFCFCF"),
Array(1, SetVertexColor, "g2_7", "#CFCFCF"),
Array(1, SetVertexColor, "g2_8", "#CFCFCF"),
Array(1, SetVertexColor, "g2_9", "#CFCFCF"),
Array(1, SetVertexColor, "g2_10", "#CFCFCF"),
Array(1, SetVertexColor, "g2_11", "#CFCFCF"),
Array(1, SetVertexColor, "g2_12", "#CFCFCF"),
Array(1, SetVertexColor, "g2_13", "#CFCFCF"),
Array(1, SetVertexColor, "g2_14", "#CFCFCF"),
Array(1, SetVertexColor, "g2_15", "#CFCFCF"),
Array(1, SetVertexColor, "g2_16", "#CFCFCF"),
Array(1, SetVertexColor, "g2_17", "#CFCFCF"),
Array(1, SetVertexColor, "g2_18", "#CFCFCF"),
Array(1, SetVertexColor, "g2_1", "blue"),
Array(1, SetVertexColor, "g2_1", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetEdgeColor, "g2_1-2", "yellow"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetEdgeColor, "g2_1-2", "grey"),
Array(1, SetEdgeColor, "g2_1-3", "yellow"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetEdgeColor, "g2_1-3", "grey"),
Array(1, SetEdgeColor, "g2_1-4", "yellow"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetEdgeColor, "g2_1-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexColor, "g2_2", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetEdgeColor, "g2_2-6", "yellow"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetEdgeColor, "g2_2-6", "grey"),
Array(1, SetEdgeColor, "g2_2-5", "yellow"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetEdgeColor, "g2_2-5", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexColor, "g2_3", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetEdgeColor, "g2_3-7", "yellow"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetEdgeColor, "g2_3-7", "grey"),
Array(1, SetEdgeColor, "g2_3-6", "yellow"),
Array(1, SetEdgeColor, "g2_3-6", "grey"),
Array(1, SetEdgeColor, "g2_3-8", "yellow"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetEdgeColor, "g2_3-8", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexColor, "g2_4", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetEdgeColor, "g2_4-8", "yellow"),
Array(1, SetEdgeColor, "g2_4-8", "grey"),
Array(1, SetEdgeColor, "g2_4-9", "yellow"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetEdgeColor, "g2_4-9", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexColor, "g2_6", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetEdgeColor, "g2_6-11", "yellow"),
Array(1, SetVertexColor, "g2_11", "blue"),
Array(1, SetVertexColor, "g2_11", "blue"),
Array(1, SetEdgeColor, "g2_6-11", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexColor, "g2_5", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetEdgeColor, "g2_5-10", "yellow"),
Array(1, SetVertexColor, "g2_10", "blue"),
Array(1, SetVertexColor, "g2_10", "blue"),
Array(1, SetEdgeColor, "g2_5-10", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexColor, "g2_7", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetEdgeColor, "g2_7-12", "yellow"),
Array(1, SetVertexColor, "g2_12", "blue"),
Array(1, SetVertexColor, "g2_12", "blue"),
Array(1, SetEdgeColor, "g2_7-12", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexColor, "g2_8", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetEdgeColor, "g2_8-13", "yellow"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetEdgeColor, "g2_8-13", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexColor, "g2_9", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetEdgeColor, "g2_9-14", "yellow"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetEdgeColor, "g2_9-14", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexColor, "g2_11", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexFrameWidth, "g2_11", "6"),
Array(1, SetVertexFrameWidth, "g2_11", "6"),
Array(1, SetEdgeColor, "g2_11-15", "yellow"),
Array(1, SetVertexColor, "g2_15", "blue"),
Array(1, SetVertexColor, "g2_15", "blue"),
Array(1, SetEdgeColor, "g2_11-15", "grey"),
Array(1, SetEdgeColor, "g2_11-16", "yellow"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetEdgeColor, "g2_11-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_11", "0"),
Array(1, SetVertexColor, "g2_10", "grey"),
Array(1, SetVertexFrameWidth, "g2_11", "0"),
Array(1, SetVertexFrameWidth, "g2_10", "6"),
Array(1, SetVertexFrameWidth, "g2_10", "6"),
Array(1, SetEdgeColor, "g2_10-15", "yellow"),
Array(1, SetEdgeColor, "g2_10-15", "grey"),
Array(1, SetVertexFrameWidth, "g2_10", "0"),
Array(1, SetVertexColor, "g2_12", "grey"),
Array(1, SetVertexFrameWidth, "g2_10", "0"),
Array(1, SetVertexFrameWidth, "g2_12", "6"),
Array(1, SetVertexFrameWidth, "g2_12", "6"),
Array(1, SetEdgeColor, "g2_12-16", "yellow"),
Array(1, SetEdgeColor, "g2_12-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_12", "0"),
Array(1, SetVertexColor, "g2_13", "grey"),
Array(1, SetVertexFrameWidth, "g2_12", "0"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetEdgeColor, "g2_13-17", "yellow"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetEdgeColor, "g2_13-17", "grey"),
Array(1, SetEdgeColor, "g2_13-16", "yellow"),
Array(1, SetEdgeColor, "g2_13-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexColor, "g2_14", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetEdgeColor, "g2_14-17", "yellow"),
Array(1, SetEdgeColor, "g2_14-17", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexColor, "g2_15", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexFrameWidth, "g2_15", "6"),
Array(1, SetVertexFrameWidth, "g2_15", "6"),
Array(1, SetEdgeColor, "g2_15-18", "yellow"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetEdgeColor, "g2_15-18", "grey"),
Array(1, SetVertexFrameWidth, "g2_15", "0"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g2_15-18", "red"),
Array(1, SetVertexColor, "g2_15", "red"),
Array(1, SetEdgeColor, "g2_11-15", "red"),
Array(1, SetVertexColor, "g2_11", "red"),
Array(1, SetEdgeColor, "g2_6-11", "red"),
Array(1, SetVertexColor, "g2_6", "red"),
Array(1, SetEdgeColor, "g2_2-6", "red"),
Array(1, SetVertexColor, "g2_2", "red"),
Array(1, SetEdgeColor, "g2_1-2", "red"),
Array(1, SetVertexColor, "g2_1", "red"),
Array(1, ShowActive, "l_14"),
Array(9, ShowActive, "l_15"),
Array(9, SetEdgeColor, "g2_6-11", "#FFAAAA"),
Array(1, BlinkEdge, "g2_15-18", "gray"),
Array(1, SetVertexColor, "g2_15", "red"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g1_15-18", "#9999FF"),
Array(3, AddEdge, "g2_18-15"),
Array(1, BlinkEdge, "g2_11-15", "gray"),
Array(1, SetVertexColor, "g2_11", "red"),
Array(1, SetVertexColor, "g2_15", "gray"),
Array(1, SetEdgeColor, "g1_11-15", "#9999FF"),
Array(3, AddEdge, "g2_15-11"),
Array(1, BlinkEdge, "g2_6-11", "gray"),
Array(1, SetVertexColor, "g2_6", "red"),
Array(1, SetVertexColor, "g2_11", "gray"),
Array(1, SetEdgeColor, "g1_6-11", "blue"),
Array(3, DeleteEdge, "g2_6-11", "1"),
Array(1, AddEdge, "g2_11-6"),
Array(1, BlinkEdge, "g2_2-6", "gray"),
Array(1, SetVertexColor, "g2_2", "red"),
Array(1, SetVertexColor, "g2_6", "gray"),
Array(1, SetEdgeColor, "g1_2-6", "#9999FF"),
Array(3, AddEdge, "g2_6-2"),
Array(1, BlinkEdge, "g2_1-2", "gray"),
Array(1, SetVertexColor, "g2_1", "green"),
Array(1, SetVertexColor, "g2_2", "gray"),
Array(1, SetEdgeColor, "g1_1-2", "#9999FF"),
Array(3, AddEdge, "g2_2-1"),
Array(1, ShowActive, "l_12"),
Array(1, UpdateEdgeInfo, "g1_1-2", "Edge1-2-flow:50of141"),
Array(1, UpdateEdgeInfo, "g1_15-18", "Edge15-18-flow:50of112"),
Array(1, UpdateEdgeInfo, "g1_2-6", "Edge2-6-flow:50of112"),
Array(1, UpdateEdgeInfo, "g1_6-11", "Edge6-11-flow:50of50"),
Array(1, UpdateEdgeInfo, "g1_11-15", "Edge11-15-flow:50of100"),
Array(1, UpdateGraphInfo, "g2_", "delta=50"),
Array(1, UpdateEdgeInfo, "g2_2-1", "Edge2-1-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_6-2", "Edge6-2-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_1-2", "Edge1-2-residualcapacity:91"),
Array(1, UpdateEdgeInfo, "g2_15-11", "Edge15-11-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_18-15", "Edge18-15-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_2-6", "Edge2-6-residualcapacity:62"),
Array(1, UpdateEdgeInfo, "g2_15-18", "Edge15-18-residualcapacity:62"),
Array(1, UpdateEdgeInfo, "g2_11-15", "Edge11-15-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_11-6", "Edge11-6-residualcapacity:50"),
Array(9, ShowActive, "l_13"),
Array(8, SetAllEdgesColor, "g2_#DDDDDD"),
Array(2, SetAllVerticesColor, "g2_#000099"),
Array(2, SetVertexColor, "g2_1", "#CFCFCF"),
Array(1, SetVertexColor, "g2_2", "#CFCFCF"),
Array(1, SetVertexColor, "g2_3", "#CFCFCF"),
Array(1, SetVertexColor, "g2_4", "#CFCFCF"),
Array(1, SetVertexColor, "g2_5", "#CFCFCF"),
Array(1, SetVertexColor, "g2_6", "#CFCFCF"),
Array(1, SetVertexColor, "g2_7", "#CFCFCF"),
Array(1, SetVertexColor, "g2_8", "#CFCFCF"),
Array(1, SetVertexColor, "g2_9", "#CFCFCF"),
Array(1, SetVertexColor, "g2_10", "#CFCFCF"),
Array(1, SetVertexColor, "g2_11", "#CFCFCF"),
Array(1, SetVertexColor, "g2_12", "#CFCFCF"),
Array(1, SetVertexColor, "g2_13", "#CFCFCF"),
Array(1, SetVertexColor, "g2_14", "#CFCFCF"),
Array(1, SetVertexColor, "g2_15", "#CFCFCF"),
Array(1, SetVertexColor, "g2_16", "#CFCFCF"),
Array(1, SetVertexColor, "g2_17", "#CFCFCF"),
Array(1, SetVertexColor, "g2_18", "#CFCFCF"),
Array(1, SetVertexColor, "g2_1", "blue"),
Array(1, SetVertexColor, "g2_1", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetEdgeColor, "g2_1-2", "yellow"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetEdgeColor, "g2_1-2", "grey"),
Array(1, SetEdgeColor, "g2_1-3", "yellow"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetEdgeColor, "g2_1-3", "grey"),
Array(1, SetEdgeColor, "g2_1-4", "yellow"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetEdgeColor, "g2_1-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexColor, "g2_2", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetEdgeColor, "g2_2-6", "yellow"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetEdgeColor, "g2_2-6", "grey"),
Array(1, SetEdgeColor, "g2_2-5", "yellow"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetEdgeColor, "g2_2-5", "grey"),
Array(1, SetEdgeColor, "g2_2-1", "yellow"),
Array(1, SetEdgeColor, "g2_2-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexColor, "g2_3", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetEdgeColor, "g2_3-7", "yellow"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetEdgeColor, "g2_3-7", "grey"),
Array(1, SetEdgeColor, "g2_3-6", "yellow"),
Array(1, SetEdgeColor, "g2_3-6", "grey"),
Array(1, SetEdgeColor, "g2_3-8", "yellow"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetEdgeColor, "g2_3-8", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexColor, "g2_4", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetEdgeColor, "g2_4-8", "yellow"),
Array(1, SetEdgeColor, "g2_4-8", "grey"),
Array(1, SetEdgeColor, "g2_4-9", "yellow"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetEdgeColor, "g2_4-9", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexColor, "g2_6", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetEdgeColor, "g2_6-2", "yellow"),
Array(1, SetEdgeColor, "g2_6-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexColor, "g2_5", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetEdgeColor, "g2_5-10", "yellow"),
Array(1, SetVertexColor, "g2_10", "blue"),
Array(1, SetVertexColor, "g2_10", "blue"),
Array(1, SetEdgeColor, "g2_5-10", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexColor, "g2_7", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetEdgeColor, "g2_7-12", "yellow"),
Array(1, SetVertexColor, "g2_12", "blue"),
Array(1, SetVertexColor, "g2_12", "blue"),
Array(1, SetEdgeColor, "g2_7-12", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexColor, "g2_8", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetEdgeColor, "g2_8-13", "yellow"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetEdgeColor, "g2_8-13", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexColor, "g2_9", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetEdgeColor, "g2_9-14", "yellow"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetEdgeColor, "g2_9-14", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexColor, "g2_10", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexFrameWidth, "g2_10", "6"),
Array(1, SetVertexFrameWidth, "g2_10", "6"),
Array(1, SetEdgeColor, "g2_10-15", "yellow"),
Array(1, SetVertexColor, "g2_15", "blue"),
Array(1, SetVertexColor, "g2_15", "blue"),
Array(1, SetEdgeColor, "g2_10-15", "grey"),
Array(1, SetVertexFrameWidth, "g2_10", "0"),
Array(1, SetVertexColor, "g2_12", "grey"),
Array(1, SetVertexFrameWidth, "g2_10", "0"),
Array(1, SetVertexFrameWidth, "g2_12", "6"),
Array(1, SetVertexFrameWidth, "g2_12", "6"),
Array(1, SetEdgeColor, "g2_12-16", "yellow"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetEdgeColor, "g2_12-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_12", "0"),
Array(1, SetVertexColor, "g2_13", "grey"),
Array(1, SetVertexFrameWidth, "g2_12", "0"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetEdgeColor, "g2_13-17", "yellow"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetEdgeColor, "g2_13-17", "grey"),
Array(1, SetEdgeColor, "g2_13-16", "yellow"),
Array(1, SetEdgeColor, "g2_13-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexColor, "g2_14", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetEdgeColor, "g2_14-17", "yellow"),
Array(1, SetEdgeColor, "g2_14-17", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexColor, "g2_15", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexFrameWidth, "g2_15", "6"),
Array(1, SetVertexFrameWidth, "g2_15", "6"),
Array(1, SetEdgeColor, "g2_15-18", "yellow"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetEdgeColor, "g2_15-18", "grey"),
Array(1, SetEdgeColor, "g2_15-11", "yellow"),
Array(1, SetVertexColor, "g2_11", "blue"),
Array(1, SetVertexColor, "g2_11", "blue"),
Array(1, SetEdgeColor, "g2_15-11", "grey"),
Array(1, SetVertexFrameWidth, "g2_15", "0"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g2_15-18", "red"),
Array(1, SetVertexColor, "g2_15", "red"),
Array(1, SetEdgeColor, "g2_10-15", "red"),
Array(1, SetVertexColor, "g2_10", "red"),
Array(1, SetEdgeColor, "g2_5-10", "red"),
Array(1, SetVertexColor, "g2_5", "red"),
Array(1, SetEdgeColor, "g2_2-5", "red"),
Array(1, SetVertexColor, "g2_2", "red"),
Array(1, SetEdgeColor, "g2_1-2", "red"),
Array(1, SetVertexColor, "g2_1", "red"),
Array(1, ShowActive, "l_14"),
Array(9, ShowActive, "l_15"),
Array(9, SetEdgeColor, "g2_5-10", "#FFAAAA"),
Array(1, BlinkEdge, "g2_15-18", "gray"),
Array(1, SetVertexColor, "g2_15", "red"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g1_15-18", "#9999FF"),
Array(3, BlinkEdge, "g2_10-15", "gray"),
Array(1, SetVertexColor, "g2_10", "red"),
Array(1, SetVertexColor, "g2_15", "gray"),
Array(1, SetEdgeColor, "g1_10-15", "#9999FF"),
Array(3, AddEdge, "g2_15-10"),
Array(1, BlinkEdge, "g2_5-10", "gray"),
Array(1, SetVertexColor, "g2_5", "red"),
Array(1, SetVertexColor, "g2_10", "gray"),
Array(1, SetEdgeColor, "g1_5-10", "blue"),
Array(3, DeleteEdge, "g2_5-10", "1"),
Array(1, AddEdge, "g2_10-5"),
Array(1, BlinkEdge, "g2_2-5", "gray"),
Array(1, SetVertexColor, "g2_2", "red"),
Array(1, SetVertexColor, "g2_5", "gray"),
Array(1, SetEdgeColor, "g1_2-5", "#9999FF"),
Array(3, AddEdge, "g2_5-2"),
Array(1, BlinkEdge, "g2_1-2", "gray"),
Array(1, SetVertexColor, "g2_1", "green"),
Array(1, SetVertexColor, "g2_2", "gray"),
Array(1, SetEdgeColor, "g1_1-2", "#9999FF"),
Array(4, ShowActive, "l_12"),
Array(1, UpdateEdgeInfo, "g1_10-15", "Edge10-15-flow:50of112"),
Array(1, UpdateEdgeInfo, "g1_2-5", "Edge2-5-flow:50of100"),
Array(1, UpdateEdgeInfo, "g1_1-2", "Edge1-2-flow:100of141"),
Array(1, UpdateEdgeInfo, "g1_15-18", "Edge15-18-flow:100of112"),
Array(1, UpdateEdgeInfo, "g1_5-10", "Edge5-10-flow:50of50"),
Array(1, UpdateEdgeInfo, "g2_2-1", "Edge2-1-residualcapacity:100"),
Array(1, UpdateEdgeInfo, "g2_10-15", "Edge10-15-residualcapacity:62"),
Array(1, UpdateEdgeInfo, "g2_2-5", "Edge2-5-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_1-2", "Edge1-2-residualcapacity:41"),
Array(1, UpdateEdgeInfo, "g2_18-15", "Edge18-15-residualcapacity:100"),
Array(1, UpdateEdgeInfo, "g2_15-18", "Edge15-18-residualcapacity:12"),
Array(1, UpdateEdgeInfo, "g2_15-10", "Edge15-10-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_10-5", "Edge10-5-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_5-2", "Edge5-2-residualcapacity:50"),
Array(9, ShowActive, "l_13"),
Array(8, SetAllEdgesColor, "g2_#DDDDDD"),
Array(2, SetAllVerticesColor, "g2_#000099"),
Array(2, SetVertexColor, "g2_1", "#CFCFCF"),
Array(1, SetVertexColor, "g2_2", "#CFCFCF"),
Array(1, SetVertexColor, "g2_3", "#CFCFCF"),
Array(1, SetVertexColor, "g2_4", "#CFCFCF"),
Array(1, SetVertexColor, "g2_5", "#CFCFCF"),
Array(1, SetVertexColor, "g2_6", "#CFCFCF"),
Array(1, SetVertexColor, "g2_7", "#CFCFCF"),
Array(1, SetVertexColor, "g2_8", "#CFCFCF"),
Array(1, SetVertexColor, "g2_9", "#CFCFCF"),
Array(1, SetVertexColor, "g2_10", "#CFCFCF"),
Array(1, SetVertexColor, "g2_11", "#CFCFCF"),
Array(1, SetVertexColor, "g2_12", "#CFCFCF"),
Array(1, SetVertexColor, "g2_13", "#CFCFCF"),
Array(1, SetVertexColor, "g2_14", "#CFCFCF"),
Array(1, SetVertexColor, "g2_15", "#CFCFCF"),
Array(1, SetVertexColor, "g2_16", "#CFCFCF"),
Array(1, SetVertexColor, "g2_17", "#CFCFCF"),
Array(1, SetVertexColor, "g2_18", "#CFCFCF"),
Array(1, SetVertexColor, "g2_1", "blue"),
Array(1, SetVertexColor, "g2_1", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetEdgeColor, "g2_1-2", "yellow"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetEdgeColor, "g2_1-2", "grey"),
Array(1, SetEdgeColor, "g2_1-3", "yellow"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetEdgeColor, "g2_1-3", "grey"),
Array(1, SetEdgeColor, "g2_1-4", "yellow"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetEdgeColor, "g2_1-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexColor, "g2_2", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetEdgeColor, "g2_2-6", "yellow"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetEdgeColor, "g2_2-6", "grey"),
Array(1, SetEdgeColor, "g2_2-5", "yellow"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetEdgeColor, "g2_2-5", "grey"),
Array(1, SetEdgeColor, "g2_2-1", "yellow"),
Array(1, SetEdgeColor, "g2_2-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexColor, "g2_3", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetEdgeColor, "g2_3-7", "yellow"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetEdgeColor, "g2_3-7", "grey"),
Array(1, SetEdgeColor, "g2_3-6", "yellow"),
Array(1, SetEdgeColor, "g2_3-6", "grey"),
Array(1, SetEdgeColor, "g2_3-8", "yellow"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetEdgeColor, "g2_3-8", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexColor, "g2_4", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetEdgeColor, "g2_4-8", "yellow"),
Array(1, SetEdgeColor, "g2_4-8", "grey"),
Array(1, SetEdgeColor, "g2_4-9", "yellow"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetEdgeColor, "g2_4-9", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexColor, "g2_6", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetEdgeColor, "g2_6-2", "yellow"),
Array(1, SetEdgeColor, "g2_6-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexColor, "g2_5", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetEdgeColor, "g2_5-2", "yellow"),
Array(1, SetEdgeColor, "g2_5-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexColor, "g2_7", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetEdgeColor, "g2_7-12", "yellow"),
Array(1, SetVertexColor, "g2_12", "blue"),
Array(1, SetVertexColor, "g2_12", "blue"),
Array(1, SetEdgeColor, "g2_7-12", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexColor, "g2_8", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetEdgeColor, "g2_8-13", "yellow"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetEdgeColor, "g2_8-13", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexColor, "g2_9", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetEdgeColor, "g2_9-14", "yellow"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetEdgeColor, "g2_9-14", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexColor, "g2_12", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexFrameWidth, "g2_12", "6"),
Array(1, SetVertexFrameWidth, "g2_12", "6"),
Array(1, SetEdgeColor, "g2_12-16", "yellow"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetEdgeColor, "g2_12-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_12", "0"),
Array(1, SetVertexColor, "g2_13", "grey"),
Array(1, SetVertexFrameWidth, "g2_12", "0"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetEdgeColor, "g2_13-17", "yellow"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetEdgeColor, "g2_13-17", "grey"),
Array(1, SetEdgeColor, "g2_13-16", "yellow"),
Array(1, SetEdgeColor, "g2_13-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexColor, "g2_14", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetEdgeColor, "g2_14-17", "yellow"),
Array(1, SetEdgeColor, "g2_14-17", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexColor, "g2_16", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexFrameWidth, "g2_16", "6"),
Array(1, SetVertexFrameWidth, "g2_16", "6"),
Array(1, SetEdgeColor, "g2_16-18", "yellow"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetEdgeColor, "g2_16-18", "grey"),
Array(1, SetVertexFrameWidth, "g2_16", "0"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g2_16-18", "red"),
Array(1, SetVertexColor, "g2_16", "red"),
Array(1, SetEdgeColor, "g2_12-16", "red"),
Array(1, SetVertexColor, "g2_12", "red"),
Array(1, SetEdgeColor, "g2_7-12", "red"),
Array(1, SetVertexColor, "g2_7", "red"),
Array(1, SetEdgeColor, "g2_3-7", "red"),
Array(1, SetVertexColor, "g2_3", "red"),
Array(1, SetEdgeColor, "g2_1-3", "red"),
Array(1, SetVertexColor, "g2_1", "red"),
Array(1, ShowActive, "l_14"),
Array(9, ShowActive, "l_15"),
Array(9, SetEdgeColor, "g2_7-12", "#FFAAAA"),
Array(1, BlinkEdge, "g2_16-18", "gray"),
Array(1, SetVertexColor, "g2_16", "red"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g1_16-18", "#9999FF"),
Array(3, AddEdge, "g2_18-16"),
Array(1, BlinkEdge, "g2_12-16", "gray"),
Array(1, SetVertexColor, "g2_12", "red"),
Array(1, SetVertexColor, "g2_16", "gray"),
Array(1, SetEdgeColor, "g1_12-16", "#9999FF"),
Array(3, AddEdge, "g2_16-12"),
Array(1, BlinkEdge, "g2_7-12", "gray"),
Array(1, SetVertexColor, "g2_7", "red"),
Array(1, SetVertexColor, "g2_12", "gray"),
Array(1, SetEdgeColor, "g1_7-12", "blue"),
Array(3, DeleteEdge, "g2_7-12", "1"),
Array(1, AddEdge, "g2_12-7"),
Array(1, BlinkEdge, "g2_3-7", "gray"),
Array(1, SetVertexColor, "g2_3", "red"),
Array(1, SetVertexColor, "g2_7", "gray"),
Array(1, SetEdgeColor, "g1_3-7", "#9999FF"),
Array(3, AddEdge, "g2_7-3"),
Array(1, BlinkEdge, "g2_1-3", "gray"),
Array(1, SetVertexColor, "g2_1", "green"),
Array(1, SetVertexColor, "g2_3", "gray"),
Array(1, SetEdgeColor, "g1_1-3", "#9999FF"),
Array(3, AddEdge, "g2_3-1"),
Array(1, ShowActive, "l_12"),
Array(1, UpdateEdgeInfo, "g1_1-3", "Edge1-3-flow:50of100"),
Array(1, UpdateEdgeInfo, "g1_7-12", "Edge7-12-flow:50of50"),
Array(1, UpdateEdgeInfo, "g1_12-16", "Edge12-16-flow:50of100"),
Array(1, UpdateEdgeInfo, "g1_3-7", "Edge3-7-flow:50of100"),
Array(1, UpdateEdgeInfo, "g1_16-18", "Edge16-18-flow:50of100"),
Array(1, UpdateEdgeInfo, "g2_7-3", "Edge7-3-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_1-3", "Edge1-3-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_12-16", "Edge12-16-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_3-7", "Edge3-7-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_18-16", "Edge18-16-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_16-18", "Edge16-18-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_12-7", "Edge12-7-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_16-12", "Edge16-12-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_3-1", "Edge3-1-residualcapacity:50"),
Array(9, ShowActive, "l_13"),
Array(9, SetAllEdgesColor, "g2_#DDDDDD"),
Array(2, SetAllVerticesColor, "g2_#000099"),
Array(2, SetVertexColor, "g2_1", "#CFCFCF"),
Array(1, SetVertexColor, "g2_2", "#CFCFCF"),
Array(1, SetVertexColor, "g2_3", "#CFCFCF"),
Array(1, SetVertexColor, "g2_4", "#CFCFCF"),
Array(1, SetVertexColor, "g2_5", "#CFCFCF"),
Array(1, SetVertexColor, "g2_6", "#CFCFCF"),
Array(1, SetVertexColor, "g2_7", "#CFCFCF"),
Array(1, SetVertexColor, "g2_8", "#CFCFCF"),
Array(1, SetVertexColor, "g2_9", "#CFCFCF"),
Array(1, SetVertexColor, "g2_10", "#CFCFCF"),
Array(1, SetVertexColor, "g2_11", "#CFCFCF"),
Array(1, SetVertexColor, "g2_12", "#CFCFCF"),
Array(1, SetVertexColor, "g2_13", "#CFCFCF"),
Array(1, SetVertexColor, "g2_14", "#CFCFCF"),
Array(1, SetVertexColor, "g2_15", "#CFCFCF"),
Array(1, SetVertexColor, "g2_16", "#CFCFCF"),
Array(1, SetVertexColor, "g2_17", "#CFCFCF"),
Array(1, SetVertexColor, "g2_18", "#CFCFCF"),
Array(1, SetVertexColor, "g2_1", "blue"),
Array(1, SetVertexColor, "g2_1", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetEdgeColor, "g2_1-2", "yellow"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetEdgeColor, "g2_1-2", "grey"),
Array(1, SetEdgeColor, "g2_1-3", "yellow"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetEdgeColor, "g2_1-3", "grey"),
Array(1, SetEdgeColor, "g2_1-4", "yellow"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetEdgeColor, "g2_1-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexColor, "g2_2", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetEdgeColor, "g2_2-6", "yellow"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetEdgeColor, "g2_2-6", "grey"),
Array(1, SetEdgeColor, "g2_2-5", "yellow"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetEdgeColor, "g2_2-5", "grey"),
Array(1, SetEdgeColor, "g2_2-1", "yellow"),
Array(1, SetEdgeColor, "g2_2-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexColor, "g2_3", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetEdgeColor, "g2_3-7", "yellow"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetEdgeColor, "g2_3-7", "grey"),
Array(1, SetEdgeColor, "g2_3-6", "yellow"),
Array(1, SetEdgeColor, "g2_3-6", "grey"),
Array(1, SetEdgeColor, "g2_3-8", "yellow"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetEdgeColor, "g2_3-8", "grey"),
Array(1, SetEdgeColor, "g2_3-1", "yellow"),
Array(1, SetEdgeColor, "g2_3-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexColor, "g2_4", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetEdgeColor, "g2_4-8", "yellow"),
Array(1, SetEdgeColor, "g2_4-8", "grey"),
Array(1, SetEdgeColor, "g2_4-9", "yellow"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetEdgeColor, "g2_4-9", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexColor, "g2_6", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetEdgeColor, "g2_6-2", "yellow"),
Array(1, SetEdgeColor, "g2_6-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexColor, "g2_5", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetEdgeColor, "g2_5-2", "yellow"),
Array(1, SetEdgeColor, "g2_5-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexColor, "g2_7", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetEdgeColor, "g2_7-3", "yellow"),
Array(1, SetEdgeColor, "g2_7-3", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexColor, "g2_8", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetEdgeColor, "g2_8-13", "yellow"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetEdgeColor, "g2_8-13", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexColor, "g2_9", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetEdgeColor, "g2_9-14", "yellow"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetEdgeColor, "g2_9-14", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexColor, "g2_13", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetVertexFrameWidth, "g2_13", "6"),
Array(1, SetEdgeColor, "g2_13-17", "yellow"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetEdgeColor, "g2_13-17", "grey"),
Array(1, SetEdgeColor, "g2_13-16", "yellow"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetVertexColor, "g2_16", "blue"),
Array(1, SetEdgeColor, "g2_13-16", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexColor, "g2_14", "grey"),
Array(1, SetVertexFrameWidth, "g2_13", "0"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetEdgeColor, "g2_14-17", "yellow"),
Array(1, SetEdgeColor, "g2_14-17", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexColor, "g2_17", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexFrameWidth, "g2_17", "6"),
Array(1, SetVertexFrameWidth, "g2_17", "6"),
Array(1, SetEdgeColor, "g2_17-18", "yellow"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetEdgeColor, "g2_17-18", "grey"),
Array(1, SetVertexFrameWidth, "g2_17", "0"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g2_17-18", "red"),
Array(1, SetVertexColor, "g2_17", "red"),
Array(1, SetEdgeColor, "g2_13-17", "red"),
Array(1, SetVertexColor, "g2_13", "red"),
Array(1, SetEdgeColor, "g2_8-13", "red"),
Array(1, SetVertexColor, "g2_8", "red"),
Array(1, SetEdgeColor, "g2_3-8", "red"),
Array(1, SetVertexColor, "g2_3", "red"),
Array(1, SetEdgeColor, "g2_1-3", "red"),
Array(1, SetVertexColor, "g2_1", "red"),
Array(1, ShowActive, "l_14"),
Array(9, ShowActive, "l_15"),
Array(9, SetEdgeColor, "g2_8-13", "#FFAAAA"),
Array(1, BlinkEdge, "g2_17-18", "gray"),
Array(1, SetVertexColor, "g2_17", "red"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g1_17-18", "#9999FF"),
Array(3, AddEdge, "g2_18-17"),
Array(1, BlinkEdge, "g2_13-17", "gray"),
Array(1, SetVertexColor, "g2_13", "red"),
Array(1, SetVertexColor, "g2_17", "gray"),
Array(1, SetEdgeColor, "g1_13-17", "#9999FF"),
Array(3, AddEdge, "g2_17-13"),
Array(1, BlinkEdge, "g2_8-13", "gray"),
Array(1, SetVertexColor, "g2_8", "red"),
Array(1, SetVertexColor, "g2_13", "gray"),
Array(1, SetEdgeColor, "g1_8-13", "blue"),
Array(3, DeleteEdge, "g2_8-13", "1"),
Array(1, AddEdge, "g2_13-8"),
Array(1, BlinkEdge, "g2_3-8", "gray"),
Array(1, SetVertexColor, "g2_3", "red"),
Array(1, SetVertexColor, "g2_8", "gray"),
Array(1, SetEdgeColor, "g1_3-8", "#9999FF"),
Array(3, AddEdge, "g2_8-3"),
Array(1, BlinkEdge, "g2_1-3", "gray"),
Array(1, SetVertexColor, "g2_1", "green"),
Array(1, SetVertexColor, "g2_3", "gray"),
Array(1, SetEdgeColor, "g1_1-3", "blue"),
Array(3, DeleteEdge, "g2_1-3", "1"),
Array(1, ShowActive, "l_12"),
Array(1, UpdateEdgeInfo, "g1_1-3", "Edge1-3-flow:100of100"),
Array(1, UpdateEdgeInfo, "g1_8-13", "Edge8-13-flow:50of50"),
Array(1, UpdateEdgeInfo, "g1_13-17", "Edge13-17-flow:50of100"),
Array(1, UpdateEdgeInfo, "g1_17-18", "Edge17-18-flow:50of112"),
Array(1, UpdateEdgeInfo, "g1_3-8", "Edge3-8-flow:50of112"),
Array(1, UpdateEdgeInfo, "g2_13-17", "Edge13-17-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_13-8", "Edge13-8-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_18-17", "Edge18-17-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_8-3", "Edge8-3-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_17-13", "Edge17-13-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_17-18", "Edge17-18-residualcapacity:62"),
Array(1, UpdateEdgeInfo, "g2_3-1", "Edge3-1-residualcapacity:100"),
Array(1, UpdateEdgeInfo, "g2_3-8", "Edge3-8-residualcapacity:62"),
Array(9, ShowActive, "l_13"),
Array(8, SetAllEdgesColor, "g2_#DDDDDD"),
Array(2, SetAllVerticesColor, "g2_#000099"),
Array(2, SetVertexColor, "g2_1", "#CFCFCF"),
Array(1, SetVertexColor, "g2_2", "#CFCFCF"),
Array(1, SetVertexColor, "g2_3", "#CFCFCF"),
Array(1, SetVertexColor, "g2_4", "#CFCFCF"),
Array(1, SetVertexColor, "g2_5", "#CFCFCF"),
Array(1, SetVertexColor, "g2_6", "#CFCFCF"),
Array(1, SetVertexColor, "g2_7", "#CFCFCF"),
Array(1, SetVertexColor, "g2_8", "#CFCFCF"),
Array(1, SetVertexColor, "g2_9", "#CFCFCF"),
Array(1, SetVertexColor, "g2_10", "#CFCFCF"),
Array(1, SetVertexColor, "g2_11", "#CFCFCF"),
Array(1, SetVertexColor, "g2_12", "#CFCFCF"),
Array(1, SetVertexColor, "g2_13", "#CFCFCF"),
Array(1, SetVertexColor, "g2_14", "#CFCFCF"),
Array(1, SetVertexColor, "g2_15", "#CFCFCF"),
Array(1, SetVertexColor, "g2_16", "#CFCFCF"),
Array(1, SetVertexColor, "g2_17", "#CFCFCF"),
Array(1, SetVertexColor, "g2_18", "#CFCFCF"),
Array(1, SetVertexColor, "g2_1", "blue"),
Array(1, SetVertexColor, "g2_1", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetEdgeColor, "g2_1-2", "yellow"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetEdgeColor, "g2_1-2", "grey"),
Array(1, SetEdgeColor, "g2_1-4", "yellow"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetEdgeColor, "g2_1-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexColor, "g2_2", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetEdgeColor, "g2_2-6", "yellow"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetEdgeColor, "g2_2-6", "grey"),
Array(1, SetEdgeColor, "g2_2-5", "yellow"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetEdgeColor, "g2_2-5", "grey"),
Array(1, SetEdgeColor, "g2_2-1", "yellow"),
Array(1, SetEdgeColor, "g2_2-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexColor, "g2_4", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetEdgeColor, "g2_4-8", "yellow"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetEdgeColor, "g2_4-8", "grey"),
Array(1, SetEdgeColor, "g2_4-9", "yellow"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetEdgeColor, "g2_4-9", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexColor, "g2_6", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetEdgeColor, "g2_6-2", "yellow"),
Array(1, SetEdgeColor, "g2_6-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexColor, "g2_5", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetEdgeColor, "g2_5-2", "yellow"),
Array(1, SetEdgeColor, "g2_5-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexColor, "g2_8", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetEdgeColor, "g2_8-3", "yellow"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetEdgeColor, "g2_8-3", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexColor, "g2_9", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetEdgeColor, "g2_9-14", "yellow"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetVertexColor, "g2_14", "blue"),
Array(1, SetEdgeColor, "g2_9-14", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexColor, "g2_3", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetEdgeColor, "g2_3-7", "yellow"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetEdgeColor, "g2_3-7", "grey"),
Array(1, SetEdgeColor, "g2_3-6", "yellow"),
Array(1, SetEdgeColor, "g2_3-6", "grey"),
Array(1, SetEdgeColor, "g2_3-8", "yellow"),
Array(1, SetEdgeColor, "g2_3-8", "grey"),
Array(1, SetEdgeColor, "g2_3-1", "yellow"),
Array(1, SetEdgeColor, "g2_3-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexColor, "g2_14", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetVertexFrameWidth, "g2_14", "6"),
Array(1, SetEdgeColor, "g2_14-17", "yellow"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetVertexColor, "g2_17", "blue"),
Array(1, SetEdgeColor, "g2_14-17", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexColor, "g2_7", "grey"),
Array(1, SetVertexFrameWidth, "g2_14", "0"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetEdgeColor, "g2_7-3", "yellow"),
Array(1, SetEdgeColor, "g2_7-3", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexColor, "g2_17", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, SetVertexFrameWidth, "g2_17", "6"),
Array(1, SetVertexFrameWidth, "g2_17", "6"),
Array(1, SetEdgeColor, "g2_17-18", "yellow"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetVertexColor, "g2_18", "blue"),
Array(1, SetEdgeColor, "g2_17-18", "grey"),
Array(1, SetEdgeColor, "g2_17-13", "yellow"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetVertexColor, "g2_13", "blue"),
Array(1, SetEdgeColor, "g2_17-13", "grey"),
Array(1, SetVertexFrameWidth, "g2_17", "0"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g2_17-18", "red"),
Array(1, SetVertexColor, "g2_17", "red"),
Array(1, SetEdgeColor, "g2_14-17", "red"),
Array(1, SetVertexColor, "g2_14", "red"),
Array(1, SetEdgeColor, "g2_9-14", "red"),
Array(1, SetVertexColor, "g2_9", "red"),
Array(1, SetEdgeColor, "g2_4-9", "red"),
Array(1, SetVertexColor, "g2_4", "red"),
Array(1, SetEdgeColor, "g2_1-4", "red"),
Array(1, SetVertexColor, "g2_1", "red"),
Array(1, ShowActive, "l_14"),
Array(9, ShowActive, "l_15"),
Array(9, SetEdgeColor, "g2_9-14", "#FFAAAA"),
Array(1, BlinkEdge, "g2_17-18", "gray"),
Array(1, SetVertexColor, "g2_17", "red"),
Array(1, SetVertexColor, "g2_18", "red"),
Array(1, SetEdgeColor, "g1_17-18", "#9999FF"),
Array(4, BlinkEdge, "g2_14-17", "gray"),
Array(1, SetVertexColor, "g2_14", "red"),
Array(1, SetVertexColor, "g2_17", "gray"),
Array(1, SetEdgeColor, "g1_14-17", "#9999FF"),
Array(3, AddEdge, "g2_17-14"),
Array(1, BlinkEdge, "g2_9-14", "gray"),
Array(1, SetVertexColor, "g2_9", "red"),
Array(1, SetVertexColor, "g2_14", "gray"),
Array(1, SetEdgeColor, "g1_9-14", "blue"),
Array(3, DeleteEdge, "g2_9-14", "1"),
Array(1, AddEdge, "g2_14-9"),
Array(1, BlinkEdge, "g2_4-9", "gray"),
Array(1, SetVertexColor, "g2_4", "red"),
Array(2, SetVertexColor, "g2_9", "gray"),
Array(1, SetEdgeColor, "g1_4-9", "#9999FF"),
Array(3, AddEdge, "g2_9-4"),
Array(1, BlinkEdge, "g2_1-4", "gray"),
Array(1, SetVertexColor, "g2_1", "green"),
Array(1, SetVertexColor, "g2_4", "gray"),
Array(1, SetEdgeColor, "g1_1-4", "#9999FF"),
Array(3, AddEdge, "g2_4-1"),
Array(2, ShowActive, "l_12"),
Array(1, UpdateEdgeInfo, "g1_14-17", "Edge14-17-flow:50of112"),
Array(1, UpdateEdgeInfo, "g1_4-9", "Edge4-9-flow:50of100"),
Array(1, UpdateEdgeInfo, "g1_9-14", "Edge9-14-flow:50of50"),
Array(1, UpdateEdgeInfo, "g1_1-4", "Edge1-4-flow:50of141"),
Array(1, UpdateEdgeInfo, "g1_17-18", "Edge17-18-flow:100of112"),
Array(1, UpdateEdgeInfo, "g2_14-17", "Edge14-17-residualcapacity:62"),
Array(1, UpdateEdgeInfo, "g2_9-4", "Edge9-4-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_14-9", "Edge14-9-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_4-9", "Edge4-9-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_18-17", "Edge18-17-residualcapacity:100"),
Array(1, UpdateEdgeInfo, "g2_17-14", "Edge17-14-residualcapacity:50"),
Array(1, UpdateEdgeInfo, "g2_1-4", "Edge1-4-residualcapacity:91"),
Array(1, UpdateEdgeInfo, "g2_17-18", "Edge17-18-residualcapacity:12"),
Array(1, UpdateEdgeInfo, "g2_4-1", "Edge4-1-residualcapacity:50"),
Array(9, ShowActive, "l_13"),
Array(9, SetAllEdgesColor, "g2_#DDDDDD"),
Array(2, SetAllVerticesColor, "g2_#000099"),
Array(2, SetVertexColor, "g2_1", "#CFCFCF"),
Array(1, SetVertexColor, "g2_2", "#CFCFCF"),
Array(1, SetVertexColor, "g2_3", "#CFCFCF"),
Array(1, SetVertexColor, "g2_4", "#CFCFCF"),
Array(1, SetVertexColor, "g2_5", "#CFCFCF"),
Array(1, SetVertexColor, "g2_6", "#CFCFCF"),
Array(1, SetVertexColor, "g2_7", "#CFCFCF"),
Array(1, SetVertexColor, "g2_8", "#CFCFCF"),
Array(1, SetVertexColor, "g2_9", "#CFCFCF"),
Array(1, SetVertexColor, "g2_10", "#CFCFCF"),
Array(1, SetVertexColor, "g2_11", "#CFCFCF"),
Array(1, SetVertexColor, "g2_12", "#CFCFCF"),
Array(1, SetVertexColor, "g2_13", "#CFCFCF"),
Array(1, SetVertexColor, "g2_14", "#CFCFCF"),
Array(1, SetVertexColor, "g2_15", "#CFCFCF"),
Array(1, SetVertexColor, "g2_16", "#CFCFCF"),
Array(1, SetVertexColor, "g2_17", "#CFCFCF"),
Array(1, SetVertexColor, "g2_18", "#CFCFCF"),
Array(1, SetVertexColor, "g2_1", "blue"),
Array(1, SetVertexColor, "g2_1", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetVertexFrameWidth, "g2_1", "6"),
Array(1, SetEdgeColor, "g2_1-2", "yellow"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetVertexColor, "g2_2", "blue"),
Array(1, SetEdgeColor, "g2_1-2", "grey"),
Array(1, SetEdgeColor, "g2_1-4", "yellow"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetVertexColor, "g2_4", "blue"),
Array(1, SetEdgeColor, "g2_1-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexColor, "g2_2", "grey"),
Array(1, SetVertexFrameWidth, "g2_1", "0"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetVertexFrameWidth, "g2_2", "6"),
Array(1, SetEdgeColor, "g2_2-6", "yellow"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetVertexColor, "g2_6", "blue"),
Array(1, SetEdgeColor, "g2_2-6", "grey"),
Array(1, SetEdgeColor, "g2_2-5", "yellow"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetVertexColor, "g2_5", "blue"),
Array(1, SetEdgeColor, "g2_2-5", "grey"),
Array(1, SetEdgeColor, "g2_2-1", "yellow"),
Array(1, SetEdgeColor, "g2_2-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexColor, "g2_4", "grey"),
Array(1, SetVertexFrameWidth, "g2_2", "0"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetVertexFrameWidth, "g2_4", "6"),
Array(1, SetEdgeColor, "g2_4-8", "yellow"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetVertexColor, "g2_8", "blue"),
Array(1, SetEdgeColor, "g2_4-8", "grey"),
Array(1, SetEdgeColor, "g2_4-9", "yellow"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetVertexColor, "g2_9", "blue"),
Array(1, SetEdgeColor, "g2_4-9", "grey"),
Array(1, SetEdgeColor, "g2_4-1", "yellow"),
Array(1, SetEdgeColor, "g2_4-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexColor, "g2_6", "grey"),
Array(1, SetVertexFrameWidth, "g2_4", "0"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetVertexFrameWidth, "g2_6", "6"),
Array(1, SetEdgeColor, "g2_6-2", "yellow"),
Array(1, SetEdgeColor, "g2_6-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexColor, "g2_5", "grey"),
Array(1, SetVertexFrameWidth, "g2_6", "0"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetVertexFrameWidth, "g2_5", "6"),
Array(1, SetEdgeColor, "g2_5-2", "yellow"),
Array(1, SetEdgeColor, "g2_5-2", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexColor, "g2_8", "grey"),
Array(1, SetVertexFrameWidth, "g2_5", "0"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetVertexFrameWidth, "g2_8", "6"),
Array(1, SetEdgeColor, "g2_8-3", "yellow"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetVertexColor, "g2_3", "blue"),
Array(1, SetEdgeColor, "g2_8-3", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexColor, "g2_9", "grey"),
Array(1, SetVertexFrameWidth, "g2_8", "0"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetVertexFrameWidth, "g2_9", "6"),
Array(1, SetEdgeColor, "g2_9-4", "yellow"),
Array(1, SetEdgeColor, "g2_9-4", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexColor, "g2_3", "grey"),
Array(1, SetVertexFrameWidth, "g2_9", "0"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetVertexFrameWidth, "g2_3", "6"),
Array(1, SetEdgeColor, "g2_3-7", "yellow"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetVertexColor, "g2_7", "blue"),
Array(1, SetEdgeColor, "g2_3-7", "grey"),
Array(1, SetEdgeColor, "g2_3-6", "yellow"),
Array(1, SetEdgeColor, "g2_3-6", "grey"),
Array(1, SetEdgeColor, "g2_3-8", "yellow"),
Array(1, SetEdgeColor, "g2_3-8", "grey"),
Array(1, SetEdgeColor, "g2_3-1", "yellow"),
Array(1, SetEdgeColor, "g2_3-1", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexColor, "g2_7", "grey"),
Array(1, SetVertexFrameWidth, "g2_3", "0"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetVertexFrameWidth, "g2_7", "6"),
Array(1, SetEdgeColor, "g2_7-3", "yellow"),
Array(1, SetEdgeColor, "g2_7-3", "grey"),
Array(1, SetVertexFrameWidth, "g2_7", "0"),
Array(1, ShowActive, "l_14"),
Array(9, ShowActive, "l_17"),
Array(9, ShowActive, "l_12"),
Array(9, ShowActive, "l_19"),
Array(9, SetAllVerticesColor, "g1_red"),
Array(2, SetVertexColor, "g1_1", "green"),
Array(1, SetVertexColor, "g1_2", "green"),
Array(1, SetVertexColor, "g1_4", "green"),
Array(1, SetVertexColor, "g1_6", "green"),
Array(1, SetEdgeColor, "g1_6-11", "yellow"),
Array(1, SetVertexColor, "g1_5", "green"),
Array(1, SetEdgeColor, "g1_5-10", "yellow"),
Array(1, SetVertexColor, "g1_8", "green"),
Array(1, SetEdgeColor, "g1_8-13", "yellow"),
Array(1, SetVertexColor, "g1_9", "green"),
Array(1, SetEdgeColor, "g1_9-14", "yellow"),
Array(1, SetVertexColor, "g1_3", "green"),
Array(1, SetVertexColor, "g1_7", "green"),
Array(1, SetEdgeColor, "g1_7-12", "yellow")
);


init();

